version: '3.3'

services:
    frontend:
        depends_on:
            - app
        build:
            context: ./frontend/
        ports:
            - "8080:80"
        restart: unless-stopped
        networks:
            - intern
    app:
        depends_on:
            - db
        build:
            context: ./backend/
        ports:
            - "5000:5000"
        restart: unless-stopped
        environment:
            DBHOST: db
            DBUSER: postgres
            DBPASSWORD: secret
        networks:
            - intern
            - db

    db:
        image: postgres:11
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: secret
            POSTGRES_DB: app
        networks:
            db:

            
networks:
    db:
    intern:

